#Python uses Mersenne Twister as its random number generator. The algorithm is based on the Mersenne Twister pseudo-random number generator. 
import random
a = random.seed() #This  will ensure that the random  numbers generated by the program are consistent across multiple runs.
b = random.randrange() #This  function returns a randomly generated integer between 0 and the number specified as its argument.
#random.radrage(start,stop[,step]) Given a starting number(start), and the last number(stop), this function is used to generate random numbers with the specified increment(step)
c = random.radint(1,5) #This  will generate a random integer between 1 and  5 (both inclusive).
d = random.random()  # This will generate a random float number between 0.00000 and 0.9999.
e = random.random() * 5 # This will generate a random float number between 0.0000 and 4.9999. Multiplication is used instead of inserting number in brackets because the console givesthe output as it is invalid code.
